#!/bin/bash

BINDIR=$(cd $(dirname $0) && pwd)

. ${BINDIR}/common
. ${BINDIR}/functions

logOutput

stopWebSocketServer
stopWSServer
runPreStopScripts

echo "Stopping fppd"
killall -9 fppd

runPostStopScripts

